name: Tests
on:
  push:

jobs:
  core-tests:
    name: Core tests
    runs-on: codeberg-small
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: https://github.com/actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - name: Setup sbt
        uses: https://github.com/sbt/setup-sbt@v1
      - name: Run core tests
        run: |
          sbt core/test

  cli-tests:
    name: CLI tests
    runs-on: codeberg-small
    needs: core-tests
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: https://github.com/actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - name: Setup sbt
        uses: https://github.com/sbt/setup-sbt@v1
      - name: Run CLI tests
        run: |
          sbt cli/test

  latex-tests:
    name: LaTeX Tests
    runs-on: codeberg-small
    needs: cli-tests
    steps:
      - uses: actions/checkout@v6
      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base
      - name: Download boxproof.sty
        run: |
          curl -sSfL https://github.com/YunkaiZhang233/boxproof/raw/refs/heads/main/boxproof.sty -o test/latex/boxproof.sty
      - name: Run LaTeX tests
        run: |
          cd test
          ./test_latex.sh

  typst-tests:
    name: Typst Tests
    runs-on: codeberg-small
    needs: cli-tests
    steps:
      - uses: actions/checkout@v6
      - uses: https://github.com/typst-community/setup-typst@v4
      - name: Run Typst tests
        run: |
          cd test
          ./test_typst.sh

  lean-tests:
    name: Lean Tests
    runs-on: codeberg-small
    needs: cli-tests
    steps:
      - uses: actions/checkout@v6
      - name: Install Lean
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
          source $HOME/.elan/env
          lean --version
      - name: Run Lean tests
        run: |
          cd test
          ./test_lean.sh

  playground-upload:
    name: Publish web ui
    runs-on: codeberg-small
    needs: [latex-tests, typst-tests, lean-tests]
    if: github.event_name != 'pull_request' && (startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: https://github.com/actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: sbt
      - name: Setup sbt
        uses: https://github.com/sbt/setup-sbt@v1
      - name: Setup nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Build webui
        run: |
          npm ci
          npm run build
      - name: Deploy to Github Pages
        uses: actions/git-pages@v2
        with:
          site: https://xiaoshihou.codeberg.page/ndpc
          token: ${{ forge.token }}
          source: dist
